site_name: Superposition
docs_dir: src
site_dir: public
use_directory_urls: false
site_url: https://thetrustypwo.github.io/Superposition
theme:
  name: material
  # custom_dir: src/overrides
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.path
    - toc.integrate
    - search.suggest
repo_url: https://github.com/TheTrustyPwo/Superposition
edit_uri: edit/master/src/
copyright: Text is available under the <a href="https://github.com/TheTrustyPwo/Superposition/blob/master/LICENSE.txt">GNU General Public License v3.0</a> License<br/>Copyright &copy; 2024 by <a href="https://github.com/TheTrustyPwo">https://github.com/TheTrustyPwo</a>
extra_javascript:
  - javascript/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - stylesheet/style.css

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
      tex_inline_wrap: ['$', '$']
      tex_block_wrap: ['$$', '$$']
  - pymdownx.highlight
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - meta
  - md_in_html

plugins:
  - mkdocs-simple-hooks:
      hooks:
        on_env: "hooks:on_env"
  - search
#  - literate-nav:
#      nav_file: navigation.md
  - git-revision-date-localized:
      enable_creation_date: true
      enabled: !ENV [MKDOCS_ENABLE_GIT_REVISION_DATE, False]
  - macros

nav:
  - Home: index.md
  - Introduction:
      - Introduction: text/introduction/main.md
  - Interference:
      - Interference: text/interference/main.md
  - Diffraction:
      - Diffraction: text/diffraction/main.md
  - Simulations:
      - Two Source Interference: simulations/two_source_interference.md
      - Single Slit Diffraction: simulations/single_slit_diffraction.md
      - Double Slit Diffraction: simulations/double_slit_diffraction.md
      - N Slit Diffraction: simulations/n_slit_diffraction.md
  - Game:
      - Under Construction: text/game/main.md